package com.yarsi.rescuepet.ui.theme

import androidx.compose.ui.graphics.Color

// Light — Palet RescuePet (terracotta/sage/ocean)
val LightPrimary = Color(0xFFAD2C00)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD34011)
val LightOnPrimaryContainer = Color(0xFFFFFBFE)
val LightSecondary = Color(0xFF1B6D24)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFA0F399)
val LightOnSecondaryContainer = Color(0xFF217128)
val LightTertiary = Color(0xFF00609A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF0B79BF)
val LightOnTertiaryContainer = Color(0xFFFDFCFF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF9F9F9)
val LightOnBackground = Color(0xFF1A1C1C)
val LightSurface = Color(0xFFF9F9F9)
val LightOnSurface = Color(0xFF1A1C1C)
val LightSurfaceVariant = Color(0xFFE2E2E2)
val LightOnSurfaceVariant = Color(0xFF5A413A)
val LightOutline = Color(0xFF8F7068)
val LightOutlineVariant = Color(0xFFE3BEB5)
val LightInverseSurface = Color(0xFF2F3131)
val LightInverseOnSurface = Color(0xFFF1F1F1)
val LightInversePrimary = Color(0xFFFFB5A0)
val LightSurfaceTint = Color(0xFFB12D00)

// Dark — diturunkan dari DESIGN.md (inverse colors)
val DarkPrimary = Color(0xFFFFB5A0)
val DarkOnPrimary = Color(0xFF3B0900)
val DarkPrimaryContainer = Color(0xFF872000)
val DarkOnPrimaryContainer = Color(0xFFFFDBD1)
val DarkSecondary = Color(0xFF88D982)
val DarkOnSecondary = Color(0xFF002204)
val DarkSecondaryContainer = Color(0xFF005312)
val DarkOnSecondaryContainer = Color(0xFFA3F69C)
val DarkTertiary = Color(0xFF99CBFF)
val DarkOnTertiary = Color(0xFF001D34)
val DarkTertiaryContainer = Color(0xFF004A78)
val DarkOnTertiaryContainer = Color(0xFFCFE5FF)
val DarkError = Color(0xFFFFDAD6)
val DarkOnError = Color(0xFF93000A)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1C)
val DarkOnBackground = Color(0xFFF1F1F1)
val DarkSurface = Color(0xFF1A1C1C)
val DarkOnSurface = Color(0xFFF1F1F1)
val DarkSurfaceVariant = Color(0xFF2F3131)
val DarkOnSurfaceVariant = Color(0xFFE3BEB5)
val DarkOutline = Color(0xFF8F7068)
val DarkOutlineVariant = Color(0xFF5A413A)
val DarkInverseSurface = Color(0xFFF9F9F9)
val DarkInverseOnSurface = Color(0xFF1A1C1C)
val DarkInversePrimary = Color(0xFFAD2C00)
val DarkSurfaceTint = Color(0xFFFFB5A0)